/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
  export interface RouteNamedMap {
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//components/DateRangePicker': RouteRecordInfo<'//components/DateRangePicker', '/components/DateRangePicker', Record<never, never>, Record<never, never>>,
    '//components/MainNav': RouteRecordInfo<'//components/MainNav', '/components/MainNav', Record<never, never>, Record<never, never>>,
    '//components/Overview': RouteRecordInfo<'//components/Overview', '/components/Overview', Record<never, never>, Record<never, never>>,
    '//components/RecentSales': RouteRecordInfo<'//components/RecentSales', '/components/RecentSales', Record<never, never>, Record<never, never>>,
    '//components/Search': RouteRecordInfo<'//components/Search', '/components/Search', Record<never, never>, Record<never, never>>,
    '//components/TeamSwitcher': RouteRecordInfo<'//components/TeamSwitcher', '/components/TeamSwitcher', Record<never, never>, Record<never, never>>,
    '//components/UserNav': RouteRecordInfo<'//components/UserNav', '/components/UserNav', Record<never, never>, Record<never, never>>,
  }  '/music/': RouteRecordInfo<'/music/', '/music', Record<never, never>, Record<never, never>>,
    '/music/components/AlbumArtwork': RouteRecordInfo<'/music/components/AlbumArtwork', '/music/components/AlbumArtwork', Record<never, never>, Record<never, never>>,
    '/music/components/Menu': RouteRecordInfo<'/music/components/Menu', '/music/components/Menu', Record<never, never>, Record<never, never>>,
    '/music/components/Podcast': RouteRecordInfo<'/music/components/Podcast', '/music/components/Podcast', Record<never, never>, Record<never, never>>,
    '/music/components/Sidebar': RouteRecordInfo<'/music/components/Sidebar', '/music/components/Sidebar', Record<never, never>, Record<never, never>>,
  }
}
